import { Colors } from '@/constants/Colors';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F7',
  },
  timelineContainer: {
    flex: 1,
    padding: 16,
  },
  topBar: {
    backgroundColor: '#53C6C6',
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: 'column',
    alignItems: 'center',
    zIndex: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    width: '100%',
  },
  logoImage: {
    height: 36,
    width: 96,
    resizeMode: 'contain',
  },
  logoText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginLeft: 8,
  },
  tripHeader: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  tripTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tripTitleInput: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    paddingVertical: 4,
    width: 200,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.3)',
  },
  dateRangeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    marginTop: 4,
  },
  dateRangeText: {
    color: '#fff',
    marginLeft: 4,
    fontSize: 14,
  },
  tripActions: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  tripActionsButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tripTotalPrice: {
    flexDirection: 'column',
    alignItems: 'center',
    marginRight: 16,
  },
  tripTotalAmount: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
  },
  previewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
  },
  publishButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.brand.coral,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  buttonText: {
    color: '#fff',
    marginLeft: 4,
    fontWeight: '600',
  },
  
  // Modal Dialog (for attractions)
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  
  // Panel Title
  panelTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#333',
  },
  
  // Attractions Search and List
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F7',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    marginLeft: 8,
    color: '#333',
  },
  categoryTabs: {
    flexDirection: 'row',
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  categoryTab: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 8,
    marginBottom: 8,
    borderRadius: 16,
    backgroundColor: '#F5F5F7',
  },
  activeTab: {
    backgroundColor: '#53C6C6',
  },
  categoryTabText: {
    color: '#555',
    fontSize: 12,
    fontWeight: '500',
  },
  activeTabText: {
    color: '#fff',
  },
  attractionsList: {
    maxHeight: 400,
  },
  attractionCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'hidden',
  },
  attractionImage: {
    width: '100%',
    height: 120,
    backgroundColor: '#F0F0F0',
  },
  categoryBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  categoryBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  attractionDetails: {
    padding: 10,
  },
  attractionName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  attractionLocation: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  attractionMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  attractionPrice: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#53C6C6',
  },
  attractionDuration: {
    fontSize: 12,
    color: '#666',
  },
  addButton: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#999',
    marginBottom: 8,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#999',
  },
  
  // Day Cards and Timeline
  daysList: {
    flex: 1,
  },
  dayCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  selectedDayCard: {
    borderWidth: 2,
    borderColor: '#53C6C6',
  },
  dayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    position: 'relative',
  },
  dayNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  dayDate: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  dayHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dayCost: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#53C6C6',
    marginRight: 8,
  },
  removeDayButton: {
    padding: 2,
  },
  emptyDayState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F9F9FB',
    borderRadius: 8,
  },
  emptyDayText: {
    marginTop: 8,
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
  },
  addActivityButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9F9FB',
    borderWidth: 1,
    borderColor: '#53C6C6',
    borderStyle: 'solid',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  addActivityButtonText: {
    marginLeft: 8,
    color: '#53C6C6',
    fontWeight: '500',
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: '#F9F9FB',
    borderRadius: 8,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  activityDragging: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  activityTimeContainer: {
    width: 60,
    backgroundColor: '#F5F5F7',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  activityTime: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  activityFlexibleTime: {
    fontSize: 11,
    color: '#666',
  },
  activityNoTime: {
    fontSize: 11,
    color: '#53C6C6',
    marginLeft: 4,
  },
  setTimeButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  activityContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  activityImage: {
    width: 40,
    height: 40,
    borderRadius: 6,
    marginRight: 8,
  },
  activityDetails: {
    flex: 1,
  },
  activityName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  activityDuration: {
    fontSize: 12,
    color: '#666',
  },
  activityBackups: {
    fontSize: 10,
    color: '#53C6C6',
    marginTop: 2,
  },
  activityPrice: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#53C6C6',
    marginLeft: 8,
  },
  addDayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#53C6C6',
    borderStyle: 'solid',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    marginBottom: 16,
  },
  addDayButtonText: {
    color: '#53C6C6',
    fontWeight: '500',
    marginLeft: 6,
  },
  
  // Bottom Sheet Content
  bottomSheetContent: {
    flex: 1,
    padding: 16,
  },
  bottomSheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 1000,
  },
  editorImageContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  editorImage: {
    width: '100%',
    height: 180,
    borderRadius: 8,
    backgroundColor: '#F0F0F0',
  },
  editorCategoryBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
  },
  editorCategoryText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  editorField: {
    marginBottom: 16,
  },
  editorLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
    marginBottom: 6,
  },
  editorInput: {
    backgroundColor: '#F5F5F7',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#333',
  },
  editorTextarea: {
    height: 120,
  },
  timeSettings: {
    marginTop: 8,
  },
  timePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F7',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  timePickerText: {
    fontSize: 16,
    color: '#333',
    marginLeft: 8,
  },
  flexibleSwitch: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  flexibleLabel: {
    fontSize: 16,
    color: '#333',
  },
  switchTrack: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#DDD',
    padding: 2,
  },
  switchTrackActive: {
    backgroundColor: '#53C6C6',
  },
  switchThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFF',
  },
  switchThumbActive: {
    transform: [{ translateX: 20 }],
  },
  editorCost: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#53C6C6',
  },
  editorDuration: {
    fontSize: 16,
    color: '#666',
  },
  backupActivity: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F5F5F7',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  backupActivityName: {
    flex: 1,
    fontSize: 14,
    color: '#333',
  },
  backupActivityRemove: {
    padding: 4,
  },
  addBackupButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    backgroundColor: '#F5F5F7',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#53C6C6',
    borderStyle: 'dashed',
  },
  addBackupText: {
    color: '#53C6C6',
    fontSize: 14,
    marginLeft: 8,
  },
  
  // Error boundary styles
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#fff',
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FF6B6B',
    marginBottom: 12,
  },
  errorMessage: {
    fontSize: 16,
    color: '#555',
    textAlign: 'center',
    marginBottom: 24,
  },
  errorButton: {
    backgroundColor: '#53C6C6',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  errorButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  bottomSheetHandle: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
  },
  bottomSheetHandleBar: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#c0c0c0',
  },
  dragHandleContainer: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 8,
  },
  modalOverlayFull: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  customBottomSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '90%',
  },
  closeButton: {
    backgroundColor: '#53C6C6',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  
  divider: {
    height: 1,
    backgroundColor: '#E0E0E0',
    marginVertical: 16,
  }
});